---
version: "3.5"
services:
  caddy:
    container_name: "caddy"
    image: caddy:2.7.4
    environment:
      - EMAIL="lang.chr86@gmail.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - {{ caddy_config_folder }}:/config
      - {{ caddy_data_folder }}:/data
      - {{ caddy_app_folder }}/Caddyfile:/etc/caddy/Caddyfile
      - /share/web/gallery:/srv/gallery
      - /share/web/fileshare:/srv/fileshare
      - /share/web/movies:/srv/movies
      - /share/web/wiki:/srv/wiki
    networks:
      - bitwarden_net
      - homeassistant_net
      - jellyfin_net

networks:
  bitwarden_net:
  homeassistant_net:
  jellyfin_net:
