# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8

automation: !include automations.yaml
group: !include group.yaml
modbus: !include modbus.yaml
rest: !include rest.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
template: !include template.yaml

recorder:
  purge_keep_days: 500
