# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8
    - 192.168.0.0/16

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

homeassistant:
  external_url: "https://home.langchr86.ch"
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config

recorder:
  purge_keep_days: 14
  exclude:
    entities:
      - sun.sun
      - weather.home
    entity_globs:
      - sensor.*_akkuspannung
      - sensor.button_*_battery
      - sensor.energy_next_*
      - sensor.sun_next_*
