# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.0.0.0/8

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

homeassistant:
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config

recorder:
  purge_keep_days: 500
