- sensor:
    - name: "Battery Power Charging"
      unit_of_measurement: W
      device_class: power
      state: "{{ max(0, 0 - states('sensor.solarnet_power_battery') | float(default=0)) }}"
    - name: "Battery Power Discharging"
      unit_of_measurement: W
      device_class: power
      state: "{{ max(0, states('sensor.solarnet_power_battery') | float(default=0)) }}"
    - name: "Power Photovoltaics"
      unit_of_measurement: W
      device_class: power
      state: "{{ states('sensor.solarnet_power_photovoltaics') | float(default=0) }}"
