---
version: "2.3"
services:
  csgoserver:
    container_name: "csgoserver"
    image: cm2network/csgo:metamod
    restart: always
    ports:
      - "27016:27016/udp"
      - "27016:27016/tcp"
      - "27021:27021/udp"
    volumes:
      - {{ cs_app_folder }}:/home/steam/csgo-dedicated/
    environment:
      - SRCDS_PORT=27016
      - SRCDS_TV_PORT=27021
      - SRCDS_RCONPW="admin"
      - SRCDS_PW="scs"
      - SRCDS_GAMETYPE=0
      - SRCDS_GAMEMODE=1 # 0 casual / 1 competitive
      # https://steamcommunity.com/dev/managegameservers
      - SRCDS_TOKEN=BCFC7F22FBA498944AE76EDD5341E1C2
      - SRCDS_MAXPLAYERS=24
      - SRCDS_STARTMAP="de_dust2"
