---
version: "2.3"
services:
  csgoserver:
    container_name: "csgoserver"
    image: cm2network/csgo:metamod
    restart: always
    ports:
      - "27016:27016/udp"
      - "27016:27016/tcp"
      - "27021:27021/udp"
    volumes:
      - {{ cs_app_folder }}:/home/steam/csgo-dedicated/
    environment:
      - SRCDS_PORT=27016
      - SRCDS_TV_PORT=27021
      - SRCDS_GAMETYPE=0
      - SRCDS_GAMEMODE=1 # 0 casual / 1 competitive
      # https://steamcommunity.com/dev/managegameservers
      - SRCDS_TOKEN=A8EA02F244D4E2EE58AD01A6E78C6634
      - SRCDS_MAXPLAYERS=24
      - SRCDS_STARTMAP="de_dust2"
      # https://developer.valvesoftware.com/wiki/CSGO_Workshop_For_Server_Operators
      # Domainname: langchr86.mooo.com
      - SRCDS_WORKSHOP_AUTHKEY=A9AD79BD43FDBBFF75373A441237A1F4
