---

- name: "Create main user group: {{ main_users_group_name }}"
  become: true
  ansible.builtin.group:
    name: "{{ main_users_group_name }}"

- ansible.builtin.include_tasks: tasks/manage_user.yml
  no_log: true
  with_items: "{{ users_users }}"
  loop_control:
    loop_var: users_user
