---

- name: "Create user: '{{ users_user.name }}'"
  become: true
  ansible.builtin.user:
    name: "{{ users_user.name }}"

- name: "Add user '{{ users_user.name }}' to group '{{ main_users_group_name }}'"
  become: true
  ansible.builtin.user:
    name: "{{ users_user.name }}"
    groups: "{{ main_users_group_name }}"
    append: true

- name: "Change password of user: '{{ users_user.name }}'"
  become: true
  ansible.builtin.user:
    name: "{{ users_user.name }}"
    password: "{{ users_user.password | password_hash('sha512', passwords.salt) }}"
  when: users_user.password is defined
