# Fronius Symo Gen24 Plus Integrations

sensor:
  - platform: integration
    source: sensor.battery_power_charging
    name: "Total Battery Energy Charged"
    unit_prefix: k
    method: left
  - platform: integration
    source: sensor.battery_power_discharging
    name: "Total Battery Energy Discharged"
    unit_prefix: k
    method: left
  - platform: integration
    source: sensor.power_photovoltaics
    name: "Total Photovoltaics Energy"
    unit_prefix: k
    method: left
  - platform: integration
    source: sensor.solarnet_power_load_others
    name: "Total SolarNet Energy others"
    unit_prefix: k
    method: left

template:
  - sensor:
      - name: "Battery Power Charging"
        unit_of_measurement: W
        device_class: power
        state: "{{ max(0, 0 - states('sensor.solarnet_power_battery') | float(default=0)) }}"
      - name: "Battery Power Discharging"
        unit_of_measurement: W
        device_class: power
        state: "{{ max(0, states('sensor.solarnet_power_battery') | float(default=0)) }}"
      - name: "Power Photovoltaics"
        unit_of_measurement: W
        device_class: power
        state: "{{ states('sensor.solarnet_power_photovoltaics') | float(default=0) }}"
      - name: "SolarNet Power load inverted"
        state: "{{ max(0, 0 - states('sensor.solarnet_power_load') | float(default=0)) }}"
        unit_of_measurement: W
        device_class: power
      - name: "SolarNet Power grid consume"
        state: "{{ max(0, states('sensor.solarnet_power_grid') | float(default=0)) }}"
        unit_of_measurement: W
        device_class: power
      - name: "SolarNet Power grid feed"
        state: "{{ max(0, 0 - states('sensor.solarnet_power_grid') | float(default=0)) }}"
        unit_of_measurement: W
        device_class: power
      - name: "SolarNet Power load others"
        state: "{{ max(0, (states('sensor.solarnet_power_load_inverted') | float(default=0))
                - (states('sensor.warmepumpe_channel_a_power') | float(default=0))
                - (states('sensor.boiler_channel_a_power') | float(default=0))
                - (states('sensor.tumbler_leistung') | float(default=0))
                - (states('sensor.waschmaschine_leistung') | float(default=0))
                - (states('sensor.enthartung_leistung') | float(default=0))
                - (states('sensor.regenwasser_leistung') | float(default=0))
                - (states('sensor.geschirrspuler_leistung') | float(default=0)) ) }}"
        unit_of_measurement: W
        device_class: power
  - binary_sensor:
      - name: "Battery Charging Aktiv"
        state: "{{ states('sensor.battery_power_charging') | int(default=0) > 10 }}"
        device_class: battery_charging
      - name: "Battery Discharging Aktiv"
        state: "{{ states('sensor.battery_power_discharging') | int(default=0) > 10 }}"
        device_class: battery
