sensor:
  - platform: systemmonitor
    scan_interval: 60
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /config
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature

binary_sensor:
  - platform: ping
    host: 192.168.0.5
    name: lang-backup
    scan_interval: 60
  - platform: ping
    host: 192.168.0.6
    name: lang-main
    scan_interval: 60
