---

kodidb_user: "{{ ansible_env.USER }}"
kodidb_group: "users"

kodidb_service_name: "kodidb"
kodidb_base_folder: "/share/config/{{ kodidb_service_name }}"
kodidb_data_folder: "{{ kodidb_base_folder }}/data"
kodidb_init_folder: "{{ kodidb_base_folder }}/init.d"
kodidb_init_file: "kodidb_init.sql"

kodidb_root_password: "kodi"
kodidb_user_name: "kodi"
kodidb_user_password: "kodi"
