---

- name: "Create systemd service file: {{ service_file_path }}"
  become: yes
  template:
    src: "templates/template.service"
    dest: "{{ service_file_path }}"
  register: service_file

- name: Reload systemd config files
  become: yes
  systemd:
    daemon_reload: yes
  when: service_file.changed

- name: "Create docker compose folder: {{ compose_service_folder }}"
  become: yes
  file:
    path: "{{ compose_service_folder }}"
    state: directory
    recurse: yes

- name: "Create docker compose file: {{ compose_file_path }}"
  become: yes
  template:
    src: "{{ compose_template }}"
    dest: "{{ compose_file_path }}"
  register: compose

- name: "Set enabled={{ service_enabled }} for: {{ service_name }}"
  become: yes
  systemd:
    name: "{{ service_name }}"
    enabled: "{{ service_enabled }}"

- name: "Start service: {{ service_name }}"
  become: yes
  systemd:
    name: "{{ service_name }}"
    state: started
  register: start

- name: "Restart service: {{ service_name }}"
  become: yes
  systemd:
    name: "{{ service_name }}"
    state: restarted
  when: not start.changed and (compose.changed or force_restart)
