---

- name: "Create systemd service file: {{ service_file_path }}"
  become: true
  ansible.builtin.template:
    src: "templates/template.service"
    dest: "{{ service_file_path }}"
    mode: "u+rw"
  register: service_file

- name: Reload systemd config files
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: service_file.changed

- name: "Create docker compose folder: {{ compose_service_folder }}"
  become: true
  ansible.builtin.file:
    path: "{{ compose_service_folder }}"
    state: directory
    mode: "u+rw"
    recurse: true

- name: "Create docker compose file: {{ compose_file_path }}"
  become: true
  ansible.builtin.template:
    src: "{{ compose_template }}"
    dest: "{{ compose_file_path }}"
    mode: "u+rw"
  register: compose

- name: "Set enabled={{ service_enabled }} for: {{ service_name }}"
  become: true
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    enabled: "{{ service_enabled }}"

- name: "Start service: {{ service_name }}"
  become: true
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
  register: start

- name: "Restart service: {{ service_name }}"
  become: true
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
  when: not start.changed and (compose.changed or force_restart)

- name: "Install automatic docker image update task for {{ service_name }}"
  ansible.builtin.include_role:
    name: systemd-timer
  vars:
    sd_timer_name: "{{ service_name }}_auto_update"
    sd_timer_command: "/usr/bin/bash -c \"/bin/systemctl reload {{ service_name }} && /bin/systemctl try-restart {{ service_name }}\""
    sd_timer_OnCalendar: "Mon *-*-* 04:00:00"
  when: auto_update
