- name: Install S.M.A.R.T tools
  become: true
  ansible.builtin.package:
    name: smartmontools

- ansible.builtin.include_tasks: tasks/enable_smart.yml
  with_items: "{{ disk_monitoring_devices }}"
  loop_control:
    loop_var: device
  when: disk_monitoring_enable_smart

- name: "Install helper scripts"
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/usr/bin/"
    owner: "root"
    group: "root"
    mode: '0755'
  with_items:
    - "disk-status"
    - "smart-long-test"
    - "smart-short-test"

- ansible.builtin.include_role:
    name: systemd-timer
  vars:
    sd_timer_name: "disk-status"
    sd_timer_command: "/bin/bash -c \"{{ disk_monitoring_disk_status_file }} > {{ disk_monitoring_status_log_path }}/disk-status.log\""
    sd_timer_OnCalendar: "*-*-* *:58:00"
    sd_timer_persistent: true
    sd_timer_user: root

- ansible.builtin.include_role:
    name: systemd-timer
  vars:
    sd_timer_name: "smart-short-test"
    sd_timer_command: "{{ disk_monitoring_short_test_file }}"
    sd_timer_OnCalendar: "*-*-* 02:28:00"
    sd_timer_persistent: true
    sd_timer_user: root
