---
version: "3"
services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:4.0.4
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - {{ transmission_config_folder }}:/config
      - {{ transmission_download_folder }}:/downloads
      - {{ transmission_watch_folder }}:/watch
    environment:
      - TZ="{{ timezone }}"
      - PUID={{ uid }}
      - PGID={{ gid }}
