- name: "Install rsync-daemon"
  become: true
  ansible.builtin.package:
    name: rsync

- name: "Create global rsyncd config: '{{ rsyncd_rsyncd_global_config }}'"
  become: true
  ansible.builtin.template:
    src: "rsyncd_global.conf"
    dest: "{{ rsyncd_rsyncd_global_config }}"
  notify: restart rsync daemon

- name: "Create rsyncd config directory: '{{ rsyncd_rsyncd_config_folder }}'"
  become: true
  ansible.builtin.file:
    path: "{{ rsyncd_rsyncd_config_folder }}"
    state: directory

- name: "Create destination modules root directory: '{{ rsyncd_destination_modules_path }}'"
  become: true
  ansible.builtin.file:
    path: "{{ rsyncd_destination_modules_path }}"
    state: directory
    mode: 0755
    group: "users"

- ansible.builtin.include_tasks: tasks/destination_modules.yml
  with_items: "{{ rsyncd_destination_modules }}"
  loop_control:
    loop_var: module

- name: "Enable rsync daemon"
  become: true
  ansible.builtin.systemd:
    name: rsync
    enabled: true
    state: started
