---

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: clang
    group: users
  with_items:
    - "{{ jdownloader_config_folder }}"
    - "{{ jdownloader_download_folder }}"

- name: "Create config file. Do edit manually later: {{ jdownloader_myjd_config_file }}"
  template:
    src: "MyJDownloaderSettings.json"
    dest: "{{ jdownloader_myjd_config_file }}"
    force: no

- include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ jdownloader_service_name }}"
