---

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: clang
    group: users
  with_items:
    - "{{ jdownloader_config_folder }}"
    - "{{ jdownloader_download_folder }}"

- name: "Create config file. Do edit manually later: {{ jdownloader_myjd_config_file }}"
  template:
    src: "MyJDownloaderSettings.json"
    dest: "{{ jdownloader_myjd_config_file }}"
    force: no

- name: Create folder for docker compose file
  become: yes
  file:
    path: "{{ jdownloader_compose_folder }}"
    state: directory

- name: Copy docker compose file
  become: yes
  template:
    src: "docker-compose.yml"
    dest: "{{ jdownloader_compose_folder }}"

- name: Enable and start docker compose service
  become: yes
  systemd:
    name: "docker-compose@{{ jdownloader_service_name }}"
    state: started
    enabled: yes
