---

- name: "Create configuration folder: '{{ jdownloader_config_folder }}'"
  become: true
  ansible.builtin.file:
    path: "{{ jdownloader_config_folder }}"
    state: directory
    owner: "{{ jdownloader_user }}"
    group: "{{ jdownloader_group }}"

- name: "Create download folder: '{{ jdownloader_download_folder }}'"
  become: true
  ansible.builtin.file:
    path: "{{ jdownloader_download_folder }}"
    state: directory
    mode: "775"
    owner: "{{ jdownloader_user }}"
    group: "{{ jdownloader_group }}"

- name: "Create MyJDownloader config file."
  ansible.builtin.template:
    src: "MyJDownloaderSettings.json"
    dest: "{{ jdownloader_myjd_config_file }}"
    mode: "644"
    force: false
  register: config

- ansible.builtin.import_tasks: tasks/evaluate_uid.yml
  vars:
    user_name: "{{ jdownloader_user }}"

- ansible.builtin.import_tasks: tasks/evaluate_gid.yml
  vars:
    group_name: "{{ jdownloader_group }}"

- ansible.builtin.include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ jdownloader_service_name }}"
    auto_restart_if_failing: true
    force_restart: "{{ config.changed }}"
