---

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jdownloader_user }}"
    group: "{{ jdownloader_group }}"
  with_items:
    - "{{ jdownloader_config_folder }}"
    - "{{ jdownloader_download_folder }}"

- name: "Create config file. Do edit manually later: {{ jdownloader_myjd_config_file }}"
  template:
    src: "MyJDownloaderSettings.json"
    dest: "{{ jdownloader_myjd_config_file }}"
    force: no

- import_tasks: tasks/evaluate_uid.yml
  vars:
    user_name: "{{ jdownloader_user }}"

- import_tasks: tasks/evaluate_gid.yml
  vars:
    group_name: "{{ jdownloader_group }}"

- include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ jdownloader_service_name }}"
