---

- name: "Create configuration folder: '{{ jdownloader_config_folder }}'"
  become: yes
  file:
    path: "{{ jdownloader_config_folder }}"
    state: directory
    owner: "{{ jdownloader_user }}"
    group: "{{ jdownloader_group }}"

- name: "Create download folder: '{{ jdownloader_download_folder }}'"
  become: yes
  file:
    path: "{{ jdownloader_download_folder }}"
    state: directory
    mode: "775"
    owner: "{{ jdownloader_user }}"
    group: "{{ jdownloader_group }}"

- name: "Create MyJDownloader config file."
  template:
    src: "MyJDownloaderSettings.json"
    dest: "{{ jdownloader_myjd_config_file }}"
    mode: "644"
    force: no
  register: config

- import_tasks: tasks/evaluate_uid.yml
  vars:
    user_name: "{{ jdownloader_user }}"

- import_tasks: tasks/evaluate_gid.yml
  vars:
    group_name: "{{ jdownloader_group }}"

- include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ jdownloader_service_name }}"
    force_restart: "{{ config.changed }}"
