---

- name: "Install example files: gallery"
  when: deploy_examples
  ansible.posix.synchronize:
    src: "files/gallery/"
    dest: "/share/web/gallery"

- name: "Install example files: fileshare"
  when: deploy_examples
  ansible.posix.synchronize:
    src: "files/fileshare/"
    dest: "/share/web/fileshare"
