---

- name: "Install example files: movies"
  when: deploy_examples
  synchronize:
    src: "files/movies/"
    dest: "/share/web/movies"

- name: "Install example files: gallery"
  when: deploy_examples
  synchronize:
    src: "files/gallery/"
    dest: "/share/web/gallery"
