---
version: "2.3"
services:
  lms:
    container_name: "lms"
    image: toertel/logitech-media-server:v8.4.0-2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{ lms_config_folder }}:/srv/squeezebox
      - {{ lms_music_folder }}:/srv/music:ro
      - {{ lms_additional_music_folder }}:/srv/additional_music:ro
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
    init: true
    networks:
      - caddy_lms_net

networks:
  caddy_lms_net:
    external: true
