---

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: clang
    group: users
  with_items:
    - "{{ transmission_config_folder }}"
    - "{{ transmission_download_folder }}/complete"
    - "{{ transmission_download_folder }}/incomplete"
    - "{{ transmission_watch_folder }}"

- name: Create folder for docker compose file
  become: yes
  file:
    path: "{{ transmission_compose_folder }}"
    state: directory

- name: Copy docker compose file
  become: yes
  template:
    src: "docker-compose.yml"
    dest: "{{ transmission_compose_folder }}"

- name: Enable and start docker compose service
  become: yes
  systemd:
    name: "docker-compose@{{ transmission_service_name }}"
    state: started
    enabled: yes
