---

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: clang
    group: users
  with_items:
    - "{{ transmission_config_folder }}"
    - "{{ transmission_download_folder }}/complete"
    - "{{ transmission_download_folder }}/incomplete"
    - "{{ transmission_watch_folder }}"

- import_tasks: tasks/evaluate_uid.yml
  vars:
    user_name: "{{ transmission_user }}"

- import_tasks: tasks/evaluate_gid.yml
  vars:
    group_name: "{{ transmission_group }}"

- include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ transmission_service_name }}"
