---

- name: Create app config folder
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "775"
  with_items:
    - "{{ app_folder }}"

- name: Create config subfolders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "u+rw"
  with_items:
    - "{{ app_folder }}"
    - "{{ app_folder }}/packages"

- name: Create core config files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ app_folder }}"
    mode: "u+rw"
  with_items:
    - "configuration.yaml"
    - "sensor.yaml"
    - "template.yaml"
  register: core_config

- name: Create package config files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ app_folder }}/packages"
    mode: "u+rw"
  with_items:
    - "packages/mystrom.yaml"
    - "packages/wpl17ics.yaml"
  register: packages

- ansible.builtin.include_role:
    name: docker-compose-service
  vars:
    service_name: "homeassistant"
    auto_restart_if_failing: true
    force_restart: "{{ core_config.changed or packages.changed }}"
    service_dependencies:
      - mosquitto.service
      - caddy.service
