---

- name: Create app config folder
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "775"
  with_items:
    - "{{ app_folder }}"

- name: Create config subfolders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ app_folder }}"

- include_role:
    name: docker-compose-service
  vars:
    service_name: "homeassistant"
    service_dependencies:
      - mosquitto.service
