---

- name: Create app config folder
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "775"
  with_items:
    - "{{ ha_config_folder }}"

- name: Create config subfolders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "u+rw"
  with_items:
    - "{{ ha_config_folder }}"
    - "{{ ha_config_folder }}/custom_components"
    - "{{ ha_config_folder }}/custom_components_download"
    - "{{ ha_config_folder }}/packages"

- name: Create core config files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ha_config_folder }}"
    mode: "u+rw"
  with_items:
    - "configuration.yaml"
  register: core_config

- name: Create package config files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ha_config_folder }}/packages"
    mode: "u+rw"
  with_items:
    - "packages/comfonet.yaml"
    - "packages/mystrom.yaml"
    - "packages/systemmonitor.yaml"
    - "packages/symogen24.yaml"
    - "packages/wpl17ics.yaml"
  register: packages

- name: Install HACS
  become: true
  ansible.builtin.shell:
    cmd: "wget -O - https://get.hacs.xyz | bash -"
    chdir: "{{ ha_config_folder }}"
    creates: "{{ ha_config_folder }}/custom_components/hacs/manifest.json"
  register: hacs

- name: Download Wattpilot integration
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/mk-maddin/wattpilot-HA/archive/refs/tags/v{{ wattpilot_version }}.tar.gz"
    remote_src: true
    dest: "{{ ha_config_folder }}/custom_components_download"
    creates: "{{ ha_config_folder }}/custom_components_download/wattpilot-HA-{{ wattpilot_version }}/hacs.json"

- name: Install Wattpilot integration
  become: true
  ansible.builtin.copy:
    src: "{{ ha_config_folder }}/custom_components_download/wattpilot-HA-{{ wattpilot_version }}/custom_components/wattpilot"
    remote_src: true
    dest: "{{ ha_config_folder }}/custom_components"
    mode: "u+rw"
  register: wattpilot_install

- ansible.builtin.include_role:
    name: docker-compose-service
  vars:
    service_name: "homeassistant"
    auto_restart_if_failing: true
    force_restart: "{{ core_config.changed or packages.changed or hacs.changed or wattpilot_install.changed }}"
    service_dependencies:
      - mosquitto.service
      - caddy.service
