---

- name: "Daemon settings: global"
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config_file }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
    insertafter: EOF
    create: true
    mode: "u+rw"
  with_items:
    - {regexp: "^X11Forwarding", line: "X11Forwarding yes"}
  notify: restart sshd

- name: "Daemon hardening: global"
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config_file }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
    insertafter: EOF
    create: true
    mode: "u+rw"
  with_items:
    - {regexp: "^PermitRootLogin", line: "PermitRootLogin yes"}
    - {regexp: "^PubkeyAuthentication", line: "PubkeyAuthentication yes"}
    - {regexp: "^ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication no"}
    - {regexp: "^AllowUsers", line: "AllowUsers {{ ssh_allowed_users|join(' ') }}"}
  notify: restart sshd

- name: "Daemon hardening: local network"
  become: true
  ansible.builtin.blockinfile:
    path: "{{ sshd_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Daemon hardening: local network"
    block: |
      PasswordAuthentication no
      Match Address 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      PasswordAuthentication yes
  notify: restart sshd
