---

- name: "Daemon settings: global"
  become: yes
  lineinfile:
    dest: "{{ sshd_config_file }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
    insertafter: EOF
    create: true
  with_items:
    - { regexp: "^X11Forwarding", line: "X11Forwarding yes" }

- name: "Daemon hardening: global"
  become: yes
  lineinfile:
    dest: "{{ sshd_config_file }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    state: present
    insertafter: EOF
    create: true
  with_items:
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin yes" }
    - { regexp: "^PubkeyAuthentication", line: "PubkeyAuthentication yes" }
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication no" }

- name: "Daemon hardening: local network"
  become: yes
  blockinfile:
    path: "{{ sshd_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Daemon hardening: local network"
    block: |
      # Allow password login only for local network
      Match Address 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      PasswordAuthentication yes
