---

- name: Install ssh tools
  become: true
  ansible.builtin.package:
    name:
      - xauth
      - openssh-client
      - openssh-server

- name: Add authorized keys
  become: true
  ansible.posix.authorized_key:
    user: "{{ ansible_env.USER }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ ssh_pub_files }}"

- name: Create users local ssh config folder
  ansible.builtin.file:
    path: "{{ ssh_user_config_folder }}"
    state: directory
    mode: "700"

- name: Add technical users private RSA key
  ansible.builtin.copy:
    src: "eddsa-key-technical-user-20230806"
    dest: "{{ ssh_user_config_folder }}/id_rsa"
    mode: "600"
  when: ssh_add_technical_user_private_key

- ansible.builtin.include_tasks: tasks/ensure_file_exists.yml
  vars:
    file_path: "{{ ssh_user_config_file }}"

- ansible.builtin.include_tasks: tasks/daemon_settings.yml
