---

- name: Install ssh tools
  become: yes
  package: name={{ item }}
  with_items:
  - xorg
  - xauth
  - openssh-client
  - openssh-server

- name: Add authorized keys
  become: yes
  authorized_key:
    user: "{{ ansible_env.USER }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items:
    - "{{ ssh_pub_files }}"

- name: Create users local ssh config folder
  file:
    path: "{{ ssh_user_config_folder }}"
    state: directory

- include_tasks: tasks/ensure_file_exists.yml
  vars:
    file_path: "{{ ssh_user_config_file }}"

- include_tasks: tasks/daemon_settings.yml
- include_tasks: tasks/host_aliases.yml
