---

# to provide
service_name: "example"
compose_template: "templates/docker-compose.yml"
service_dependencies: []
service_enabled: true
force_restart: false
auto_restart_if_failing: false

# usually not needed to change
systemd_folder: "/etc/systemd/system"
service_file_path: "{{ systemd_folder }}/{{ service_name }}.service"
compose_folder: "/etc/docker-compose"
compose_service_folder: "{{ compose_folder }}/{{ service_name }}"
compose_file_path: "{{ compose_service_folder }}/docker-compose.yml"
