---

- name: "Create wiki folder"
  become: true
  ansible.builtin.file:
    path: "{{ wiki_web_folder }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "users"
    mode: "774"

- name: "Install mdwiki framework"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ wiki_web_folder }}"
  with_items:
    - index.html
    - config.json

- name: "Install example index file"
  when: deploy_examples
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ wiki_web_folder }}"
  with_items:
    - index.md
    - navigation.md
