---

- name: Create folders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jf_user }}"
    group: "{{ jf_group }}"
    mode: "u+rw"
    recurse: true
  with_items:
    - "{{ jf_config_folder }}"

- ansible.builtin.import_tasks: tasks/evaluate_uid.yml
  vars:
    user_name: "{{ jf_user }}"

- ansible.builtin.import_tasks: tasks/evaluate_gid.yml
  vars:
    group_name: "{{ jf_group }}"

- ansible.builtin.include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ jf_service_name }}"
    auto_restart_if_failing: true
    auto_update: true
    service_dependencies:
      - caddy.service
