---

- set_fact:
    device_path: "/dev/{{ vg.label }}/{{ lv.label }}"

- name: "Ensure logical volume '{{ lv.label }}' in volume group '{{ vg.label }}' not already existing"
  become: yes
  shell: "lvdisplay {{ vg.label }} | grep {{ lv.label }}"
  register: lvdisplay
  changed_when: false
  failed_when: false
  ignore_errors: true
  no_log: true

- name: "Create logical volume: '{{ lv.label }}'"
  become: yes
  command: "lvcreate --name {{ lv.label }} {{ lv.size_options }} {{ vg.label }}"
  when: lvdisplay.rc != 0

- set_fact:
    lv_dir: "{{ vg.mount_path }}/{{ lv.label }}"

- name: "Format and mount logical volume: '{{ lv.label }}' with ext4"
  include_role:
    name: filesystem
    apply:
      become: yes
  vars:
    filesystems:
      - label: "{{ lv.label }}"
        device: "{{ device_path }}"
        mount_path: "{{ lv_dir }}"
        type: "ext4"

- name: "Ensure logical volume '{{ lv_dir }}' is accessible by 'users' group and user '{{ ansible_env.USER }}'"
  become: yes
  file:
    path: '{{ lv_dir }}'
    owner: '{{ ansible_env.USER }}'
    group: 'users'
    mode: '0775'
