---

- name: "Install LVM packages"
  become: true
  ansible.builtin.package:
    name: lvm2

- ansible.builtin.import_tasks: tasks/status-helper.yml

- ansible.builtin.include_tasks: tasks/volume_group.yml
  with_items: "{{ volume_groups }}"
  loop_control:
    loop_var: vg
