---

- name: "Install helper to show volume status: '{{ lvm_status_helper_path }}'"
  become: true
  ansible.builtin.template:
    src: "lvm-status"
    dest: "{{ lvm_status_helper_path }}"
    owner: "root"
    group: "root"
    mode: 0755

- ansible.builtin.set_fact:
    status_log_file: "{{ status_log_path }}/lvm-status.log"

- ansible.builtin.include_role:
    name: systemd-timer
  vars:
    sd_timer_name: "lvm-status"
    sd_timer_command: "/bin/bash -c \"{{ lvm_status_helper_path }} > {{ status_log_file }}\""
    sd_timer_OnCalendar: "*-*-* 03:00:00"
    sd_timer_user: root
    sd_timer_persistent: true
