---
version: "3.9"
services:
  lyrion:
    container_name: "lyrion"
    image: lmscommunity/lyrionmusicserver:9.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - {{ lyrion_config_folder }}:/config:rw
      - {{ lyrion_playlist_folder }}:/playlist:rw
      - {{ lyrion_music_folder }}:/music:ro
    # We cannot use port forwardings anymore because of docker update 28.x.x. See: gateway_mode_ipv in https://github.com/moby/moby/discussions/49497
    network_mode: host
    environment:
      - PUID={{ uid }}
      - PGID={{ gid }}
