---

- ansible.builtin.set_fact:
    ssh_known_hosts_content: "{{ lookup('template', 'templates/host.j2') }}"

- name: "Add host aliases for: '{{ host.name }}' -> '{{ host.real }}'"
  ansible.builtin.blockinfile:
    path: "{{ ssh_known_hosts_user_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: host alias: {{ host.name }}"
    block: "{{ ssh_known_hosts_content }}"
