---

ssh_allowed_users:
  - '{{ ansible_env.USER }}'

ssh_pub_files:
  - 'eddsa-key-clang-privat-20220905.opub'
  - 'eddsa-key-technical-user-20230806.opub'

sshd_config_file: "/etc/ssh/sshd_config"

ssh_user_config_folder: "{{ ansible_env.HOME }}/.ssh"
ssh_user_config_file: "{{ ssh_user_config_folder }}/config"
ssh_known_hosts_file: "{{ ssh_user_config_folder }}/known_hosts"

ssh_evaluate_host_aliases: true
ssh_host_aliases:
  - {name: '{{ hostname_main }}', real: '{{ ip_address_main }}'}
  - {name: '{{ hostname_backup }}', real: '{{ ip_address_backup }}'}
