---

- name: "Create user directory"
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ ansible_env.USER }}"
    group: "users"
  with_items: "{{ folders }}"
