---

- name: Install tmux tools
  become: true
  ansible.builtin.package:
    name:
      - tmux

- name: Add tmux config
  ansible.builtin.copy:
    src: .tmux.conf
    dest: "{{ ansible_env.HOME }}"
    mode: "u+rw"
