- name: Install tmux tools
  become: yes
  package:
    name:
      - tmux

- name: Add tmux config
  copy:
    src: .tmux.conf
    dest: "~/"

- name: Ensure Unix line endings
  replace:
    path: "~/.tmux.conf"
    regexp: "\r\n"
    replace: "\n"

