---

- name: "Create app folder: {{ cs_app_folder }}"
  become: yes
  file:
    path: "{{ cs_app_folder }}"
    state: directory
    mode: "777"
    recurse: yes

- name: "Create config folder: {{ cs_config_folder }}"
  become: yes
  file:
    path: "{{ cs_config_folder }}"
    state: directory
    mode: "777"
    recurse: yes

- name: "Copy config files to {{ cs_config_folder }}"
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ cs_config_folder }}"
  with_items:
    - "autoexec.cfg"
    - "gamemode_casual_server.cfg"
    - "gamemode_competitive_server.cfg"
  register: config

- include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ cs_service_name }}"
    service_enabled: no
    force_restart: "{{ config.changed }}"
