---

- name: "Create folders"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "777"
  with_items:
    - "{{ cs_server_folder }}"
    - "{{ cs_config_folder }}"
    - "{{ cs_config_folder }}/cfg"

- name: "Copy config files to {{ cs_config_folder }}/cfg"
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ cs_config_folder }}/cfg"
    mode: "u+rw"
  with_items:
    - "autoexec.cfg"
    - "gamemode_casual_server.cfg"
    - "gamemode_competitive2v2_server.cfg"
    - "gamemode_competitive_server.cfg"
    - "gamemode_deathmatch_server.cfg"
  register: config

- ansible.builtin.include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ cs_service_name }}"
    service_enabled: false
    force_restart: "{{ config.changed }}"
