#!/bin/bash -e

if [[ "$EUID" -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi


date
printf "\n\n"


printf "LVM physical volumes stats \n==============================\n"
pvs
printf "\n\n"

printf "LVM volume groups stats \n==============================\n"
vgs
printf "\n\n"

printf "LVM logical volumes stats \n==============================\n"
lvs
printf "\n\n"

printf "Filesystems stats \n==============================\n"
df -h
printf "\n\n"
