---

- name: "Install btrfs-progs"
  become: true
  ansible.builtin.package:
    name: "btrfs-progs"

- ansible.builtin.import_tasks: tasks/status-helper.yml
- ansible.builtin.import_tasks: tasks/samba-quota.yml

- ansible.builtin.include_tasks: tasks/volume.yml
  with_items: "{{ volumes }}"
  loop_control:
    loop_var: volume
