---

- name: Include ubuntu version specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "ubuntu_{{ ansible_distribution_release }}.yml"
    - "unknown_distro.yml"
