---

- set_fact:
    status_log_file: "{{ volume.status_log_path }}/btrfs-status-{{ volume.label }}.log"

- include_role:
    name: systemd-timer
  vars:
    sd_timer_name: "btrfs-status-{{ volume.label }}"
    sd_timer_command: "/bin/bash -c \"{{ btrfs_status_helper_path }} {{ volume.mount_path }} > {{ status_log_file }}\""
    sd_timer_OnCalendar: "*-*-* 03:00:00"
    sd_timer_user: root
    sd_timer_persistent: true
