- name: Install basic tools
  become: true
  ansible.builtin.package:
    name:
      - tree
      - nano
      - wget
      - unzip
      - tar
      - net-tools
      - inxi

- name: Install system statistics tools
  become: true
  ansible.builtin.package:
    name:
      - iotop
      - htop
      - powertop
      - sysstat
      - dstat

- name: "Set timezone to {{ timezone }}"
  become: true
  community.general.timezone:
    name: "{{ timezone }}"

- name: Set locale to en_US.UTF-8
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8

- name: Set default locale to en_US.UTF-8
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/default/locale"
    regexp: "LC_ALL"
    line: "LC_ALL=\"en_US.UTF-8\""
