- name: Install basic tools
  become: true
  package:
    name:
      - tree
      - nano
      - wget
      - unzip
      - tar
      - net-tools

- name: Install system statistics tools
  become: true
  package:
    name:
      - iotop
      - htop
      - sysstat
      - dstat

- name: "Set timezone to {{ timezone }}"
  become: true
  timezone:
    name: "{{ timezone }}"

- name: Set locale to en_US.UTF-8
  become: true
  locale_gen:
    name: en_US.UTF-8

- name: Set default locale to en_US.UTF-8
  become: true
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""
