- name: Install basic tools
  become: true
  ansible.builtin.package:
    name:
      - tree
      - nano
      - wget
      - unzip
      - tar
      - net-tools
      - inxi

- name: Install system statistics tools
  become: true
  ansible.builtin.package:
    name:
      - iotop
      - htop
      - bashtop
      - sysstat
      - dstat

- name: "Set timezone to {{ timezone }}"
  become: true
  community.general.timezone:
    name: "{{ timezone }}"

- name: Set locale to en_US.UTF-8
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8

- name: Set default locale to en_US.UTF-8
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/default/locale"
    regexp: "LC_ALL"
    line: "LC_ALL=\"en_US.UTF-8\""

- name: Remove cloud-init
  become: true
  ansible.builtin.package:
    name: cloud-init
    state: absent

- name: Remove cloud-init SSH config
  become: true
  ansible.builtin.file:
    path: "/etc/ssh/sshd_config.d/50-cloud-init.conf"
    state: absent

- name: Remove snapd
  become: true
  ansible.builtin.package:
    name: snapd
    state: absent

- name: Disable snap.lxd.activate.service
  become: true
  ansible.builtin.systemd_service:
    name: snap.lxd.activate.service
    state: 'stopped'
    enabled: false
  ignore_errors: true
