- name: Install basic tools
  become: yes
  package: name={{ item }}
  with_items:
  - tree
  - nano
  - wget
  - unzip
  - tar
  - net-tools

- name: Install system statistics tools
  become: yes
  package: name={{ item }}
  with_items:
  - iotop
  - htop
  - sysstat
  - dstat

- name: "Set timezone to {{ timezone }}"
  become: yes
  timezone:
    name: "{{ timezone }}"

- name: Set locale to en_US.UTF-8
  become: yes
  locale_gen:
    name: en_US.UTF-8

- name: Set default locale to en_US.UTF-8
  become: yes
  lineinfile: dest=/etc/default/locale
    regexp="LC_ALL"
    line="LC_ALL=\"en_US.UTF-8\""
