---

jdownloader_config_folder: "/var/local/jdownloader"
jdownloader_myjd_config_file: "{{ jdownloader_config_folder }}/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json"
jdownloader_download_folder: "/share/downloads/jdownloader"
jdownloader_service_name: "jdownloader"
