# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20230608.0.0"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--spec-ctrl", "on"]
  end

  config.vm.define "games" do |games|
    games.vm.hostname = "vm-games"
    games.vm.network "private_network", ip: "192.168.10.10"
    games.vm.network "forwarded_port", guest: 27016, host: 27016, protocol: 'tcp'   # CS2
    games.vm.network "forwarded_port", guest: 27016, host: 27016, protocol: 'udp'   # CS2
    games.vm.network "forwarded_port", guest: 27021, host: 27021, protocol: 'udp'   # CS2

    games.vm.disk :disk, size: "80GB", primary: true

    games.vm.synced_folder "../", "/vagrant"

    games.vm.provision "shell",
        inline: "/vagrant/vagrant-ansible.sh playbook_games.yml",
        privileged: false
  end
end
