---
version: "3.5"
services:
  actual:
    container_name: "actual"
    image: docker.io/actualbudget/actual-server:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - {{ actual_data_folder }}:/data
    ports:
      - 5006:5006
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - caddy_actual_net

networks:
  caddy_actual_net:
    external: true
