---

- set_fact:
    script: "{{ rsync_script_folder }}/{{ job.name }}.bash"

# we have to create a dict out of a list to be able to use a variable as key
# see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#items2dict-filter
- set_fact:
    timer_tags:
      - key: "{{ job.name }}"
        value:
          timer_command: "{{ script }}"
          timer_user: "{{ job.user | default(ansible_env.USER) }}"
          timer_persistent: yes
          timer_AccuracySec: 1m
          timer_OnCalendar: "{{ job.timer_OnCalendar | default('*-*-* 03:00:00') }}"
# see: https://www.freedesktop.org/software/systemd/man/systemd.timer.html
# for definition of value in timer_OnCalendar

# see: https://github.com/vlcty/ansible-systemd-timers
- include_role:
    name: ansible-systemd-timers
    apply:
      become: yes
  vars:
    timers:
      - "{{ timer_tags | items2dict }}"

- name: "Create job script: '{{ script }}'"
  become: yes
  template:
    src: "job_script.j2"
    dest: "{{ script }}"
    mode: "755"

- name: "Create jobs source folders (if no remote URL)"
  file:
    path: "{{ item.src }}"
    state: directory
  when: item.src is not search(":")
  with_items: "{{ job.steps }}"

- name: "Create jobs destination folders (if no remote URL)"
  file:
    path: "{{ item.dest }}"
    state: directory
  when: item.dest is not search(":")
  with_items: "{{ job.steps }}"
