---

- ansible.builtin.set_fact:
    script: "{{ rsync_script_folder }}/{{ job.name }}.bash"

- ansible.builtin.include_role:
    name: systemd-timer
  vars:
    sd_timer_name: "{{ job.name }}"
    sd_timer_command: "{{ script }}"
    sd_timer_OnCalendar: "{{ job.timer_OnCalendar | default('*-*-* 03:00:00') }}"
    sd_timer_user: "{{ job.user | default(ansible_env.USER) }}"
    sd_timer_persistent: true

- name: "Create job script: '{{ script }}'"
  become: true
  ansible.builtin.template:
    src: "job_script.j2"
    dest: "{{ script }}"
    mode: "755"

- name: "Create jobs source folders (if no remote URL)"
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: directory
    mode: "u+rw"
    owner: "{{ job.user }}"
    group: 'users'
  when: item.src is not search(":")
  with_items: "{{ job.steps }}"

- name: "Create jobs destination folders (if no remote URL)"
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: directory
    mode: "u+rw"
    owner: "{{ job.user }}"
    group: 'users'
  when: item.dest is not search(":")
  with_items: "{{ job.steps }}"
