---

- name: Install rsync
  become: true
  ansible.builtin.package:
    name: rsync

- name: "Create scripts folder: '{{ rsync_script_folder }}'"
  become: true
  ansible.builtin.file:
    path: "{{ rsync_script_folder }}"
    state: directory
    mode: "u+rw"
    recurse: true

- ansible.builtin.include_tasks: tasks/job.yml
  with_items: "{{ rsync_jobs }}"
  loop_control:
    loop_var: job
