---

- name: Install rsync
  become: yes
  package:
    name: rsync

- name: "Create scripts folder: '{{ rsync_script_folder }}'"
  become: yes
  file:
    path: "{{ rsync_script_folder }}"
    state: directory
    recurse: yes

- include_tasks: tasks/job.yml
  with_items: "{{ rsync_jobs }}"
  loop_control:
    loop_var: job
