version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2023.12
    ports:
      - "8123:8123"
      - "5683:5683/udp"
    volumes:
      - {{ ha_config_folder }}:/config
    environment:
      - TZ="{{ timezone }}"
    networks:
      - mosquitto_homeassistant_net
      - caddy_homeassistant_net

networks:
  mosquitto_homeassistant_net:
    external: true
  caddy_homeassistant_net:
    external: true
