version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2022.2
    ports:
      - "8123:8123"
    volumes:
      - /share/config/homeassistant:/config
    environment:
      - TZ="{{ timezone }}"
    networks:
      - mosquitto_homeassistant_net

networks:
  mosquitto_homeassistant_net:
    external: true
