---
version: "3.5"
services:
  bitwarden:
    container_name: "bitwarden"
    image: vaultwarden/server:1.28.1
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN={{ passwords.bitwarden_admin }}
    volumes:
      - data:/data
    networks:
      - caddy_bitwarden_net

volumes:
  data:

networks:
  caddy_bitwarden_net:
    external: true