---
version: "3.5"
services:
  bitwarden:
    container_name: "bitwarden"
    image: vaultwarden/server:1.23.1
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - data:/data
    networks:
      - caddy_bitwarden_net

volumes:
  data:

networks:
  caddy_bitwarden_net:
    external: true