---
version: "3.5"
services:
  bitwarden:
    container_name: "bitwarden"
    image: vaultwarden/server:1.34.3
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN='$argon2id$v=19$m=65540,t=3,p=4$EXqCqPnRrVAYG+Z4umgSolMWTF4bMWJqmY1rXMRaopo$Nx9LHN+JDZudYSciOkZ/hW2N82APYkS0WREiTs7cntI'
    volumes:
      - data:/data
    networks:
      - caddy_bitwarden_net
    ports:
      - 8088:80

volumes:
  data:

networks:
  caddy_bitwarden_net:
    external: true