---

- name: Create app config folder
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mb_user }}"
    group: "{{ mb_group }}"
    mode: "775"
  with_items:
    - "{{ mb_app_folder }}"

- name: Create config subfolders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "775"
  with_items:
    - "{{ mb_config_folder }}"
    - "{{ mb_data_folder }}"

- ansible.builtin.import_tasks: tasks/evaluate_uid.yml
  vars:
    user_name: "{{ mb_cert_user }}"

- ansible.builtin.import_tasks: tasks/evaluate_gid.yml
  vars:
    group_name: "{{ mb_cert_group }}"

- name: "Copy config file to {{ mb_config_folder }}"
  become: true
  ansible.builtin.template:
    src: "templates/config.ini"
    dest: "{{ mb_config_folder }}/config.ini"
    mode: "u+rw"
  register: config

- name: "Create docker compose service. Run 'docker exec -it mumble supw <new_password>' to change the super user password"
  ansible.builtin.include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ mb_service_name }}"
    force_restart: "{{ config.changed }}"

- name: "Install periodic restart timer task for {{ mb_service_name }}"
  ansible.builtin.include_role:
    name: systemd-timer
  vars:
    sd_timer_name: "{{ mb_service_name }}_periodic_restart"
    sd_timer_command: "/bin/systemctl try-restart {{ mb_service_name }}"
    sd_timer_OnCalendar: "Mon *-*-* 04:00:00"
