---

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mb_user }}"
    group: "{{ mb_group }}"
    mode: "775"
    recurse: yes
  with_items:
    - "{{ mb_app_folder }}"
    - "{{ mb_config_folder }}"
    - "{{ mb_data_folder }}"

- name: "Evaluate {{ mb_cert_user }} UID"
  command: "id -u {{ mb_cert_user }}"
  changed_when: false
  register: uid

- name: "Evaluate {{ mb_cert_group }} GID"
  command: "id -g {{ mb_cert_group }}"
  changed_when: false
  register: gid

- name: "Create docker compose service. Run 'docker exec -it mumble supw <new_password>' to change the super user password"
  include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ mb_service_name }}"
