---

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kodidb_user }}"
    group: "{{ kodidb_group }}"
    mode: "777"
  with_items:
    - "{{ kodidb_base_folder }}"
    - "{{ kodidb_init_folder }}"

- name: "Create database folder: {{ kodidb_data_folder }}"
  become: yes
  file:
    path: "{{ kodidb_data_folder }}"
    state: directory
  register: data_folder

- name: "Ensure correct user/group of database folder: {{ kodidb_data_folder }}"
  become: yes
  file:
    path: "{{ kodidb_data_folder }}"
    owner: "{{ kodidb_user }}"
    group: "{{ kodidb_group }}"
    mode: "777"

- name: Copy SQL init file
  template:
    src: "{{ kodidb_init_file }}"
    dest: "{{ kodidb_init_folder }}"
    mode: "775"

- include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ kodidb_service_name }}"

- name: Grant user rights in Mariadb for Kodi
  become: yes
  shell:
    cmd: "docker exec {{ kodidb_service_name }} /bin/sh -c '/usr/bin/mariadb --user=root --password={{ kodidb_root_password }} mysql < /init.d/{{ kodidb_init_file }}'"
  when: data_folder.changed
  retries: 10
  delay: 5
  register: dbinit
  until: dbinit.rc == 0
