- hosts: all

  pre_tasks:
    - include_vars:
        file: passwords.yml
        name: passwords
      no_log: yes
    - set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

    - import_tasks: tasks/ubuntu_apt.yml
    - import_tasks: tasks/basic_setup.yml
    - import_tasks: tasks/build_tools.yml

  roles:
    - role: users
      vars:
        users:
          - { name: "{{ main_user }}", password: "{{ main_password }}" }
          - { name: "velin", password: "{{ passwords.velin }}" }

    - role: ssh
    - role: git-tools
      vars:
        git_aliases: on
        git_rerere: on
        git_editor_nano: on
        git_prompt: on
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: share
      vars:
        share_source: "/mnt/share-main"

    - role: user_folders
      vars:
        folders:
          - "/git"
          - "/share/config/"
          - "/share/data/"
          - "/share/fileshare/"
          - "/share/gallery/"
          - "/share/lang-backup/"
          - "/share/lang-main/"
          - "/share/projects/"
          - "/share/temp/"

    - role: ansible-role-samba
      become: yes
      vars:
        samba_mitigate_cve_2017_7494: off
        samba_users:
          - name: "{{ main_user }}"
            password: "{{ main_password }}"
          - name: "velin"
            password: "{{ passwords.velin }}"
        samba_shares:
          - name: "share-main"
            path: "/share"
            browseable: on
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }} velin"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/share"
        disk_monitoring_devices:
          - path: '/dev/sda'
            smart_type: 'sat'

    - role: dockerio
    - role: jdownloader
      vars:
        myjd_password: "{{ passwords.myjd }}"

    - role: transmission
    - role: logitechmediaserver
    - role: kodidb
    - role: mumble
    - role: caddy
