- hosts: all

  pre_tasks:
    - include_vars:
        file: passwords.yml
        name: passwords

    - import_tasks: tasks/ubuntu_apt.yml
    - import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - { name: "clang", password: "{{ passwords.clang }}" }

    - role: ssh
      vars:
        ssh_pub_files: [ 'ssh_key_clang_home.opub' ]

    - role: git-tools
      vars:
        git_aliases: on
        git_rerere: on
        git_editor_nano: on
        git_prompt: on
        git_archivestotext: off
        git_docxtotext: off
        git_pdftotext: off
        git_xlsxtotext: off
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: wol
      vars:
        device: "ens130"

    - role: share
      vars:
        share_source: "/mnt/subvolumes/share-main"

    - role: rsync
      vars:
        rsync_groups:
          - name: "backups-lang-main"
            dest: "/share/backups/lang-main"
            user: "clang"
            timer_OnCalendar: "*-*-* 03:00:00"
            pre_sleep_seconds: 30
            sources:
              - "lang-main:/mnt/subvolumes/share-main"
