- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

    - ansible.builtin.import_tasks: tasks/ubuntu_apt.yml
    - ansible.builtin.import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - {name: "{{ main_user }}", password: "{{ main_password }}"}
          - {name: "velin", password: "{{ passwords.velin }}"}

    - role: ssh
      vars:
        ssh_pub_files:
          - 'eddsa-key-clang-privat-20220905.opub'
          - 'eddsa-key-clang-scs-20220830.opub'
          - 'eddsa-key-technical-user-20230806.opub'

    - role: git-tools
      vars:
        git_graphical_tools: false
        git_aliases: true
        git_rerere: true
        git_editor_nano: true
        git_prompt: true
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: btrfs
      vars:
        volumes:
          - label: "pool-main"
            mount_path: "/mnt/pool-main"
            mkfs_options: "--data raid1 --metadata raid1"
            status_log_path: "/mnt/pool-main/subvolumes/share-main"
            devices:
              - "/dev/sda"
              - "/dev/sdb"
              - "/dev/sdc"
              - "/dev/sdd"
            subvolumes:
              - "share-main"

    - role: btrbk
      vars:
        btrbk_pool_label: "pool-main"
        btrbk_mount_path: "/mnt/pool-main"
        btrbk_subvolumes:
          - name: "share-main"
            snapshot_preserve_min: "1h"
            snapshot_preserve: "48h 28d"
            timer_OnCalendar: "*-*-* *:00,30:00"

    - role: share
      vars:
        share_source: "/mnt/pool-main/subvolumes/share-main"

    - role: user_folders
      vars:
        folders:
          - "/config"
          - "/git"
          - "/share-common"
          - "/share/Audios/"
          - "/share/Bilder/"
          - "/share/Bücher/"
          - "/share/Videos/"
          - "/share/web/"
          - "/share/web/fileshare/"
          - "/share/web/gallery/"

    - role: rsync
      vars:
        rsync_jobs:
          - name: "backups-{{ hostname_main }}"
            user: "root"
            timer_OnCalendar: "*-*-* *:20:00"
            steps:
              - { src: "/config", dest: "/share/backups/{{ hostname_main }}/config", opts: '--exclude="home-assistant_v2.db*" --exclude="jellyfin" --exclude="lyrion/config/cache"' }
              - { src: "/git", dest: "/share/backups/{{ hostname_main }}/git" }
              - { src: "/share-common", dest: "/share/backups/{{ hostname_main }}/share-common" }

    - role: rsync-daemon
      vars:
        rsyncd_destination_modules_path: "/share/backups"
        rsyncd_destination_modules:
          - user_name: "{{ main_user }}"
            user_password: "{{ main_password }}"
            subfolders:
              - 'lang-ct21'
              - 'lang-xps13'
          - user_name: 'velin'
            user_password: "{{ passwords.velin }}"
            subfolders:
              - 'lang-mate'

    - role: ansible-collection-vladgh-samba
      become: true
      vars:
        samba_mitigate_cve_2017_7494: false
        samba_global_include: "samba-global-include.conf"
        samba_users:
          - name: "{{ main_user }}"
            password: "{{ main_password }}"
          - name: "velin"
            password: "{{ passwords.velin }}"
        samba_shares:
          - name: "share-main"
            path: "/mnt/pool-main/subvolumes/share-main"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }}"
          - name: "snapshots"
            path: "/mnt/pool-main/snapshots"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
          - name: "share-common"
            path: "/share-common"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }} velin"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/share"
        disk_monitoring_devices:
          - path: '/dev/sda'
          - path: '/dev/sdb'
          - path: '/dev/sdc'
          - path: '/dev/sdd'
          - path: '/dev/nvme0n1'

    - role: dockerio

    - role: ddclient
      vars:
        cloudflare_api_token: "{{ passwords.cloudflare_api_token }}"
    - role: duckdns
      vars:
        ddns_token: "{{ passwords.duckdns }}"

    - role: adguard
      vars:
        adguard_user: "{{ main_user }}"
        adguard_password: "{{ main_password }}"

    - role: transmission
    - role: jdownloader
      vars:
        myjd_password: "{{ passwords.myjd }}"

    - role: caddy
    - role: web_examples
    - role: wiki
    - role: mumble
    - role: bitwarden
    - role: mosquitto
    - role: homeassistant
    - role: jellyfin
    - role: jellyseerr
    - role: lyrion

    - role: homepage
      vars:
        homepage_adguard_user: "{{ main_user }}"
        homepage_adguard_password: "{{ main_password }}"
