- hosts: all

  pre_tasks:
  - name: Update package manager repositories
    become: yes
    apt:
      update_cache: yes
    changed_when: False

  roles:
  - role: ssh
    vars:
      ssh_pub_files: ['ssh_key_clang_home.opub']
      
  - role: git-tools
    vars:
      git_aliases: on
      git_rerere: on
      git_editor_nano: on
      git_prompt: on
      git_archivestotext: on
      git_docxtotext: on
      git_pdftotext: on
      git_xlsxtotext: on
      git_user_name: "Christian Lang"
      git_user_email: "lang.chr86@gmail.com"

  - role: bash
  - role: tmux
  - role: dockerio
  - role: docker-compose-service
  - role: transmission
