- hosts: all

  pre_tasks:
  - import_tasks: tasks/ubuntu_apt.yml
  - import_tasks: tasks/basic_setup.yml


  roles:
  - role: users



  - role: ssh
    vars:
      ssh_pub_files: ['ssh_key_clang_home.opub']

  - role: git-tools
    vars:
      git_aliases: on
      git_rerere: on
      git_editor_nano: on
      git_prompt: on
      git_archivestotext: off
      git_docxtotext: off
      git_pdftotext: off
      git_xlsxtotext: off
      git_user_name: "Christian Lang"
      git_user_email: "lang.chr86@gmail.com"

  - role: bash
  - role: tmux

  - role: wol
    vars:
      device: "ens130"

  - role: dockerio
  - role: jdownloader
    vars:
      jdownloader_download_folder: "/mnt/subvolumes/share-main/Downloads"

  - role: cs16server
  - role: csgoserver
