- hosts: all

  pre_tasks:
    - include_vars:
        file: passwords.yml
        name: passwords

    - import_tasks: tasks/ubuntu_apt.yml
    - import_tasks: tasks/basic_setup.yml
    - import_tasks: tasks/build_tools.yml

  roles:
    - role: users
      vars:
        users:
          - { name: "clang", password: "{{ passwords.clang }}" }
          - { name: "velin", password: "{{ passwords.velin }}" }

    - role: ssh
    - role: git-tools
      vars:
        git_aliases: on
        git_rerere: on
        git_editor_nano: on
        git_prompt: on
        git_archivestotext: off
        git_docxtotext: off
        git_pdftotext: off
        git_xlsxtotext: off
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux





    - role: share
      vars:
        share_source: "/mnt/share-main/share"

    - role: dockerio
    - role: jdownloader
      vars:
        myjd_password: "{{ passwords.myjd }}"

    - role: transmission
    - role: logitechmediaserver
    - role: kodidb
    - role: mumble
