- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

  roles:


    - role: lms
      vars:
        lms_music_folder: "/share/Audios/"
        lms_additional_music_folder: "/share-common/Temp"

    - role: caddy
