- hosts: all

  pre_tasks:
    - include_vars:
        file: passwords.yml
        name: passwords
    - set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

    - import_tasks: tasks/ubuntu_apt.yml
    - import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - { name: "{{ main_user }}", password: "{{ main_password }}" }

    - role: ssh
    - role: git-tools
      vars:
        git_aliases: on
        git_rerere: on
        git_editor_nano: on
        git_prompt: on
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: wol
      vars:
        device: "ens130"

    - role: lvm
      vars:
        status_log_path: "/share"
        volume_groups:
          - label: "pool-main"
            mount_path: "/mnt/pool-main"
            devices:
              - "/dev/sdb"
              - "/dev/sdc"
            logical_volumes:
              - label: "share-main"
                size_options: "-l 100%FREE"

    - role: share
      vars:
        share_source: "/mnt/pool-main/share-main"

    - role: rsync
      vars:
        rsync_jobs:
          - name: "backups-lang-main"
            user: "{{ main_user }}"
            timer_OnCalendar: "*-*-* 03:00:00"
            pre_sleep_seconds: 30
            steps:
              - { src: "{{ main_user }}@lang-main:/mnt/subvolumes/share-main", dest: "/share/backups/lang-main/share-main" }

    - role: ansible-role-samba
      become: yes
      vars:
        samba_mitigate_cve_2017_7494: off
        samba_users:
          - name: "{{ main_user }}"
            password: "{{ main_password }}"
        samba_shares:
          - name: "share-main"
            path: "/mnt/pool-main/share-main"
            browseable: on
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }}"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/share"
        disk_monitoring_devices:
          - path: '/dev/sda'
          - path: '/dev/sdb'
          - path: '/dev/sdc'
