- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

  roles:

    - role: dockerio

    - role: caddy

    - role: lyrion
    - role: lyrion-audiomuse


    - role: homepage
      vars:
        homepage_adguard_user: "{{ main_user }}"
        homepage_adguard_password: "{{ main_password }}"
