- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

    - ansible.builtin.import_tasks: tasks/ubuntu_apt.yml
    - ansible.builtin.import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - {name: "{{ main_user }}", password: "{{ main_password }}"}
          - {name: "velin", password: "{{ passwords.velin }}"}
          - {name: "kodi", password: "{{ passwords.kodi }}"}

    - role: ssh
    - role: git-tools
      vars:
        git_graphical_tools: false
        git_aliases: true
        git_rerere: true
        git_editor_nano: true
        git_prompt: true
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: wol
      vars:
        device: "ens130"

    - role: btrfs
      vars:
        volumes:
          - label: "pool-main"
            mount_path: "/mnt/pool-main"
            mkfs_options: "--data raid1 --metadata raid1"
            status_log_path: "/mnt/pool-main/subvolumes/share-main"
            devices:
              - "/dev/sdb"
              - "/dev/sdc"
              - "/dev/sdd"
            subvolumes:
              - "share-main"

    - role: btrbk
      vars:
        btrbk_pool_label: "pool-main"
        btrbk_mount_path: "/mnt/pool-main"
        btrbk_subvolumes:
          - name: "share-main"
            snapshot_preserve_min: "1h"
            snapshot_preserve: "24h 14d 5w 3m"
            timer_OnCalendar: "*-*-* *:00,30:00"

    - role: share
      vars:
        share_source: "/mnt/pool-main/subvolumes/share-main"

    - role: rsync
      vars:
        rsync_jobs:
          - name: "backups-{{ hostname_mini }}"
            user: "{{ main_user }}"
            timer_OnCalendar: "*-*-* *:10:00"
            pre_sleep_seconds: 30
            steps:
              - {src: "{{ main_user }}@{{ hostname_mini }}:/share/config", dest: "/share/backups/{{ hostname_mini }}/share-main/config", opts: '--rsync-path="sudo rsync"'}
              - {src: "{{ main_user }}@{{ hostname_mini }}:/share/data", dest: "/share/backups/{{ hostname_mini }}/share-main/data"}
              - {src: "{{ main_user }}@{{ hostname_mini }}:/share/projects", dest: "/share/backups/{{ hostname_mini }}/share-main/projects"}
              - {src: "{{ main_user }}@{{ hostname_mini }}:/share/temp", dest: "/share/backups/{{ hostname_mini }}/share-main/temp"}
              - {src: "{{ main_user }}@{{ hostname_mini }}:/share/web", dest: "/share/backups/{{ hostname_mini }}/share-main/web"}
              - {src: "{{ main_user }}@{{ hostname_mini }}:/git", dest: "/share/backups/{{ hostname_mini }}/share-main/git"}
          - name: "synced-{{ hostname_mini }}"
            user: "{{ main_user }}"
            timer_OnCalendar: "*-*-* 03:00:00"
            pre_sleep_seconds: 30
            steps:
              - {src: "/share/Audios", dest: "{{ main_user }}@{{ hostname_mini }}:/share/synced/audios"}
              - {src: "/share/Bücher/technology", dest: "{{ main_user }}@{{ hostname_mini }}:/share/synced/books/technology"}
              - {src: "/share/Bücher/magazines", dest: "{{ main_user }}@{{ hostname_mini }}:/share/synced/books/magazines"}

    - role: rsync-daemon
      vars:
        rsyncd_destination_modules_path: "/share/backups"
        rsyncd_destination_modules:
          - user_name: "{{ main_user }}"
            user_password: "{{ main_password }}"
            subfolders:
              - 'lang-ct21'
              - 'lang-xps13'
          - user_name: 'velin'
            user_password: "{{ passwords.velin }}"
            subfolders:
              - 'lang-zen11'

    - role: ansible-role-samba
      become: true
      vars:
        samba_mitigate_cve_2017_7494: false
        samba_global_include: "samba-global-include.conf"
        samba_users:
          - name: "{{ main_user }}"
            password: "{{ main_password }}"
          - name: "velin"
            password: "{{ passwords.velin }}"
          - name: "kodi"
            password: "{{ passwords.kodi }}"
        samba_shares:
          - name: "share-main"
            path: "/mnt/pool-main/subvolumes/share-main"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }}"
          - name: "snapshots"
            path: "/mnt/pool-main/snapshots"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/share"
        disk_monitoring_devices:
          - path: '/dev/sda'
          - path: '/dev/sdb'
          - path: '/dev/sdc'
          - path: '/dev/sdd'

    - role: dockerio
    - role: jdownloader
      vars:
        jdownloader_config_folder: "/etc/jdownloader"
        jdownloader_download_folder: "/share/downloads"
        myjd_password: "{{ passwords.myjd }}"

    - role: cs16server
    - role: csgoserver
