- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "claudia"
        main_password: "{{ passwords.claudia }}"

    - ansible.builtin.import_tasks: tasks/ubuntu_apt.yml
    - ansible.builtin.import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users_users:
          - { name: "{{ main_user }}", password: "{{ main_password }}" }

    - role: ssh
      vars:
        ssh_pub_files:
          - 'eddsa-key-clang-privat-20220905.opub'

    - role: git-tools
      vars:
        git_graphical_tools: false
        git_aliases: true
        git_rerere: true
        git_editor_nano: true
        git_prompt: true
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: btrfs
      vars:
        volumes:
          - label: "pool-main"
            mount_path: "/mnt/pool-main"
            mkfs_options: "--data raid0 --metadata dup"
            status_log_path: "/mnt/pool-main/subvolumes/medien"
            devices:
              - "/dev/sdb"
            subvolumes:
              - "medien"

    - role: share
      vars:
        share_path: "/medien"
        share_source: "/mnt/pool-main/subvolumes/medien"

    - role: user_folders
      vars:
        folders:
          - "/config"
          - "/daten"
          - "/medien/Audios/"
          - "/medien/Bilder/"
          - "/medien/Bücher/"
          - "/medien/Videos/"

    - role: rsync
      vars:
        rsync_jobs:
          - name: "backups-{{ hostname_claudia }}"
            user: "{{ main_user }}"
            timer_OnCalendar: "*-*-* 03:00:00"
            pre_sleep_seconds: 1
            steps:
              - {src: "/daten", dest: "/medien/backups/{{ hostname_claudia }}/daten"}

    - role: rsync-daemon
      vars:
        rsyncd_destination_modules_path: "/medien/backups"
        rsyncd_destination_modules:
          - user_name: "{{ main_user }}"
            user_password: "{{ main_password }}"
            subfolders:
              - 'claudia-pc'
              - 'claudia-laptop'

    - role: ansible-collection-vladgh-samba
      become: true
      vars:
        samba_mitigate_cve_2017_7494: false
        samba_global_include: "samba-global-include.conf"
        samba_users:
          - name: "{{ main_user }}"
            password: "{{ main_password }}"
        samba_shares:
          - name: "daten"
            path: "/daten"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }}"
          - name: "medien"
            path: "/mnt/pool-main/subvolumes/medien"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }}"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/medien"
        disk_monitoring_devices:
          - path: '/dev/sda'
          - path: '/dev/sdb'

    - role: dockerio
    - role: jellyfin
