- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

    - ansible.builtin.import_tasks: tasks/ubuntu_apt.yml
    - ansible.builtin.import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - {name: "{{ main_user }}", password: "{{ main_password }}"}

    - role: ssh
    - role: git-tools
      vars:
        git_graphical_tools: false
        git_aliases: true
        git_rerere: true
        git_editor_nano: true
        git_prompt: true
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: wol
      vars:
        device: "ens130"

    - role: lvm
      vars:
        status_log_path: "/share"
        volume_groups:
          - label: "pool-main"
            mount_path: "/mnt/pool-main/subvolumes"
            devices:
              - "/dev/sdb"
              - "/dev/sdc"
            logical_volumes:
              - label: "share-main"
                size_options: "-l 100%FREE"

    - role: share
      vars:
        share_source: "/mnt/pool-main/subvolumes/share-main"

    - role: rsync
      vars:
        rsync_jobs:
          - name: "backups-{{ hostname_main }}"
            ansible.builtin.user: "{{ main_user }}"
            timer_OnCalendar: "*-*-* 03:00:00"
            pre_sleep_seconds: 30
            steps:
              - {src: "{{ main_user }}@{{ hostname_main }}:/share", dest: "/share/backups/{{ hostname_main }}/share-main"}

    - role: ansible-role-samba
      become: true
      vars:
        samba_mitigate_cve_2017_7494: false
        samba_users:
          - name: "{{ main_user }}"
            password: "{{ main_password }}"
        samba_shares:
          - name: "share-main"
            path: "/share"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }}"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/share"
        disk_monitoring_devices:
          - path: '/dev/sda'
          - path: '/dev/sdb'
          - path: '/dev/sdc'
