- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

    - ansible.builtin.import_tasks: tasks/ubuntu_apt.yml
    - ansible.builtin.import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - {name: "{{ main_user }}", password: "{{ main_password }}"}
          - {name: "velin", password: "{{ passwords.velin }}"}

    - role: ssh
    - role: git-tools
      vars:
        git_graphical_tools: false
        git_aliases: true
        git_rerere: true
        git_editor_nano: true
        git_prompt: true
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: share
      vars:
        share_source: "/mnt/share-main"

    - role: user_folders
      vars:
        folders:
          - "/git"
          - "/share/config/"
          - "/share/data/"
          - "/share/hostcontrold/"
          - "/share/projects/"
          - "/share/temp/"
          - "/share/web/"
          - "/share/web/fileshare/"
          - "/share/web/gallery/"
          - "/share/web/movies/"

    - role: ansible-collection-vladgh-samba
      become: true
      vars:
        samba_mitigate_cve_2017_7494: false
        samba_users:
          - name: "{{ main_user }}"
            password: "{{ main_password }}"
          - name: "velin"
            password: "{{ passwords.velin }}"
        samba_shares:
          - name: "share-main"
            path: "/share"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }} velin"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/share"
        disk_monitoring_devices:
          - path: '/dev/sda'
            smart_type: 'sat'

    - role: dockerio
    - role: jdownloader
      vars:
        myjd_password: "{{ passwords.myjd }}"

    - role: caddy
    - role: bitwarden
    - role: transmission
    - role: kodidb
    - role: mumble
    - role: mosquitto
    - role: homeassistant
    - role: ddclient
    - role: web_examples
    - role: wiki
