- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "kevin"
        main_password: "{{ passwords.kevin }}"
        kevin_main_disk: "/dev/sdb"
        kevin_backup_disk: "/dev/sda1"

    - ansible.builtin.import_tasks: tasks/ubuntu_apt.yml
    - ansible.builtin.import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - { name: "{{ main_user }}", password: "{{ main_password }}" }

    - role: ssh
      vars:
        ssh_evaluate_host_aliases: false
        ssh_host_aliases: []

    - role: git-tools
      vars:
        git_graphical_tools: false
        git_aliases: true
        git_rerere: true
        git_editor_nano: true
        git_prompt: true

    - role: bash
    - role: tmux

    - role: btrfs
      vars:
        volumes:
          - label: "pool-main"
            mount_path: "/mnt/pool-main"
            mkfs_options: "--data raid0 --metadata dup"
            status_log_path: "/mnt/pool-main/subvolumes/daten"
            devices:
              - "{{ kevin_main_disk }}"
            subvolumes:
              - "daten"

    - role: filesystem
      vars:
        filesystems:
          - label: "backup"
            device: "{{ kevin_backup_disk }}"
            type: "ntfs"
            mount_path: "/mnt/backup"

    - role: ansible-collection-vladgh-samba
      become: true
      vars:
        samba_mitigate_cve_2017_7494: false
        samba_global_include: "samba-global-include.conf"
        samba_users:
          - name: "{{ main_user }}"
            password: "{{ main_password }}"
        samba_shares:
          - name: "daten"
            path: "/mnt/pool-main/subvolumes/daten"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"
            write_list: "{{ main_user }}"
          - name: "backup"
            path: "/mnt/backup"
            browseable: true
            owner: "{{ main_user }}"
            group: "users"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/mnt/pool-main/subvolumes/daten"
        disk_monitoring_devices:
          - path: '/dev/sda'
          - path: '/dev/sdb'

    - role: rsync
      vars:
        rsync_jobs:
          - name: "backups-{{ hostname_kevin }}"
            user: "{{ main_user }}"
            timer_OnCalendar: "*-*-* 03:00:00"
            pre_sleep_seconds: 1
            steps:
              - {src: "/mnt/pool-main/subvolumes/daten", dest: "/mnt/backup"}

    - role: rsync-daemon
      vars:
        rsyncd_destination_modules_path: "/mnt/pool-main/subvolumes/daten/Backups"
        rsyncd_destination_modules:
          - user_name: "{{ main_user }}"
            user_password: "{{ main_password }}"
            subfolders:
              - 'kevin'
              - 'tanja'
