- hosts: all

  pre_tasks:
    - include_vars:
        file: passwords.yml
        name: passwords

    - import_tasks: tasks/ubuntu_apt.yml
    - import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - { name: "clang", password: "{{ passwords.clang }}" }

    - role: ssh
    - role: git-tools
      vars:
        git_aliases: on
        git_rerere: on
        git_editor_nano: on
        git_prompt: on
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: wol
      vars:
        device: "ens130"

    - role: share
      vars:
        share_source: "/mnt/subvolumes/share-main"

    - role: rsync
      vars:
        rsync_jobs:
          - name: "backups-lang-main"
            timer_OnCalendar: "*-*-* 03:00:00"
            pre_sleep_seconds: 30
            steps:
              - { src: "clang@lang-main:/mnt/subvolumes/share-main", dest: "/share/backups/lang-main/share-main" }

    - role: ansible-role-samba
      become: yes
      vars:
        samba_mitigate_cve_2017_7494: off
        samba_users:
          - name: "clang"
            password: "{{ passwords.clang }}"
        samba_shares:
          - name: share-main
            path: "/mnt/subvolumes/share-main"
            browseable: on
            group: users
            valid_users: +users
            write_list: clang
            include_file: "share-main-include.conf"

    - role: disk-monitoring
      vars:
        disk_monitoring_status_log_path: "/share"
        disk_monitoring_devices:
          - path: '/dev/sda'
          - path: '/dev/sdb'
          - path: '/dev/sdc'
