- hosts: all

  pre_tasks:
    - ansible.builtin.include_vars:
        file: passwords.yml
        name: passwords
      no_log: true
    - ansible.builtin.set_fact:
        main_user: "clang"
        main_password: "{{ passwords.clang }}"

    - ansible.builtin.import_tasks: tasks/ubuntu_apt.yml
    - ansible.builtin.import_tasks: tasks/basic_setup.yml

  roles:
    - role: users
      vars:
        users:
          - { name: "{{ main_user }}", password: "{{ main_password }}" }

    - role: ssh
      vars:
        ssh_pub_files:
          - 'eddsa-key-clang-privat-20220905.opub'

    - role: git-tools
      vars:
        git_graphical_tools: false
        git_aliases: true
        git_rerere: true
        git_editor_nano: true
        git_prompt: true
        git_user_name: "Christian Lang"
        git_user_email: "lang.chr86@gmail.com"

    - role: bash
    - role: tmux

    - role: user_folders
      vars:
        folders:
          - "/config"

    - role: dockerio
    - role: cs2server
    - role: csrcon
