---
version: '3.1'
services:
  kodidb:
    container_name: kodidb
    image: yobasystems/alpine-mariadb:10.11.5
    ports:
      - "3306:3306"
    volumes:
      - {{ kodidb_data_folder }}:/var/lib/mysql
      - {{ kodidb_init_folder }}:/init.d
    environment:
      MYSQL_ROOT_PASSWORD: {{ kodidb_root_password }}
      MYSQL_USER: {{ kodidb_user_name }}
      MYSQL_PASSWORD: {{ kodidb_user_password }}
