---

- name: "Create app folder: {{ caddy_app_folder }}"
  become: true
  file:
    path: "{{ caddy_app_folder }}"
    state: directory
    mode: "744"

- name: "Create config folder: {{ caddy_config_folder }}"
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "744"
  with_items:
    - "{{ caddy_config_folder }}"
    - "{{ caddy_data_folder }}"

- name: "Copy Caddyfile to {{ caddy_app_folder }}"
  become: true
  template:
    src: "templates/Caddyfile"
    dest: "{{ caddy_app_folder }}/Caddyfile"
  register: config

- include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ caddy_service_name }}"
    force_restart: "{{ config.changed }}"
