---

- name: "Create real share directory: '{{ share_source }}'"
  become: true
  ansible.builtin.file:
    path: "{{ share_source }}"
    state: directory
    mode: '0775'
    owner: "{{ ansible_env.USER }}"
    group: "users"

- name: "Create central symlink to main share: '{{ share_path }}' -> '{{ share_source }}'"
  become: true
  ansible.builtin.file:
    state: link
    path: "{{ share_path }}"
    src: "{{ share_source }}"
