---

- name: "Create config folder: {{ cs_config_folder }}"
  become: true
  ansible.builtin.file:
    path: "{{ cs_config_folder }}"
    state: directory
    mode: "644"

- name: Copy config files
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ cs_config_folder }}"
    mode: "u+rw"
  with_items:
    - "server.cfg"
    - "podbot.cfg"
    - "mapcycle.txt"
  register: config

- ansible.builtin.include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ cs_service_name }}"
    service_enabled: false
    force_restart: "{{ config.changed }}"
