---

- name: "Create config folder: {{ cs_config_folder }}"
  become: true
  file:
    path: "{{ cs_config_folder }}"
    state: directory

- name: Copy config files
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ cs_config_folder }}"
  with_items:
    - "server.cfg"
    - "podbot.cfg"
    - "mapcycle.txt"
  register: config

- include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ cs_service_name }}"
    service_enabled: false
    force_restart: "{{ config.changed }}"
