---

- name: "Create config folder: {{ cs_config_folder }}"
  become: yes
  file:
    path: "{{ cs_config_folder }}"
    state: directory

- name: Copy config files
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ cs_config_folder }}"
  with_items:
    - "server.cfg"
    - "podbot.cfg"
    - "mapcycle.txt"
  register: config

- name: Create folder for docker compose file
  become: yes
  file:
    path: "{{ cs_compose_folder }}"
    state: directory

- name: Copy docker compose file
  become: yes
  template:
    src: "docker-compose.yml"
    dest: "{{ cs_compose_folder }}"
  register: compose

- name: Start docker compose service
  become: yes
  systemd:
    name: "docker-compose@{{ cs_service_name }}"
    state: started

- name: Restart container
  become: yes
  systemd:
    name: "docker-compose@{{ cs_service_name }}"
    state: restarted
  when: compose.changed or config.changed
