---

- name: Add Docker CE GPG key
  become: true
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker CE APT repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install Docker CE and dependencies
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create group docker
  become: true
  ansible.builtin.group:
    name: docker

- name: Add docker user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    append: true
    groups: docker

- name: Install docker-compose
  become: true
  ansible.builtin.apt:
    name: docker-compose
    state: present
