---
version: "2.3"
services:
  jdownloader:
    image: jaymoulin/jdownloader:2.0.2
    container_name: jdownloader
    user: {{ uid }}:{{ gid }}
    volumes:
      - {{ jdownloader_config_folder }}:/opt/JDownloader/app/cfg
      - {{ jdownloader_download_folder }}:/opt/JDownloader/Downloads
    ports:
      - "3129:3129"
