name: ansible-lint

on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint ansible
        run: |
          sudo linting/lint.sh
