name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: macos-10.15
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: "1"
      VAGRANT_EXPERIMENTAL: "disks"

    steps:
    - uses: actions/checkout@v2

    #- name: add more IP ranges for virtualbox
    #  run: |
    #    mkdir -p /etc/vbox/
    #    echo "192.168.0.0/16" > /etc/vbox/networks.conf

    - name: Run vagrant up
      run: vagrant up
