name: vagrant-up

on: [push, pull_request]

jobs:
  vagrant-up:
    runs-on: macos-12
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: "1"

    steps:
    - uses: actions/checkout@v4

#    - name: add more IP ranges for virtualbox
#      run: |
#        mkdir -p /etc/vbox/
#        echo "192.168.0.0/16" > /etc/vbox/networks.conf

    - name: Run vagrant up
      run: vagrant up
      working-directory: .github/workflows