---

- name: Create folders
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ lms_user }}"
    group: "{{ lms_group }}"
    mode: "775"
    recurse: true
  with_items:
    - "{{ lms_music_folder }}"
    - "{{ lms_additional_music_folder }}"
    - "{{ lms_config_folder }}"

- ansible.builtin.include_role:
    name: docker-compose-service
  vars:
    service_name: "{{ lms_service_name }}"
