- ansible.builtin.set_fact:
    btrbk_config_path: "{{ btrbk_base_config_path }}/{{ btrbk_pool_label }}"

- name: "Create config directory: '{{ btrbk_config_path }}'"
  become: true
  ansible.builtin.file:
    path: "{{ btrbk_config_path }}"
    state: directory
    mode: "u+rw"

- name: "Create btrbk config for: '{{ subvolume.name }}'"
  become: true
  ansible.builtin.template:
    src: "btrbk.conf"
    dest: "{{ btrbk_config_path }}/{{ subvolume.name }}.conf"
    mode: "u+rw"
