- name: Install btrbk
  become: true
  package:
    name: btrbk

- name: "Create snapshots directory: '{{ btrbk_snapshots_path }}'"
  become: true
  file:
    path: "{{ btrbk_snapshots_path }}"
    state: directory

- include_tasks: tasks/config.yml
  with_items: "{{ btrbk_subvolumes }}"
  loop_control:
    loop_var: subvolume

- include_tasks: tasks/timer.yml
  with_items: "{{ btrbk_subvolumes }}"
  loop_control:
    loop_var: subvolume
