- name: Install btrbk
  become: true
  ansible.builtin.package:
    name: btrbk

- name: "Create snapshots directory: '{{ btrbk_snapshots_path }}'"
  become: true
  ansible.builtin.file:
    path: "{{ btrbk_snapshots_path }}"
    state: directory
    mode: "ug+rw"

- ansible.builtin.include_tasks: tasks/config.yml
  with_items: "{{ btrbk_subvolumes }}"
  loop_control:
    loop_var: subvolume

- ansible.builtin.include_tasks: tasks/timer.yml
  with_items: "{{ btrbk_subvolumes }}"
  loop_control:
    loop_var: subvolume
